language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: fxH4kMuVeKzDN1zMB359glqndfHvi7Xo3jbjpuwzIqpdeYFchQHmGptuFp8JXYjWM9VgARqz5XJfsPNK2MfvTm2fBI3jJXVvZOmjmq9NqAloO2Z1oFGBjJ81PwOHyWfiwoKLqYktbD/MEbyj9Xlgv2CpzsHRY2n4tAIQEa8RN80=
  - secure: I76TBuX9W9lwmfuUNCIFyO0XMF80R/b0GZc5d250KchWtDJXh3H5gb2ObezgBxKqv7vQ3H6/pvuTY92IuvyvO7vGi6mfK8/dQGl10NMMF9TuFYYdbJDyVBmyL4H3AAdt7mgmyIKivyDkPkQwxgENVUy7EPRtLR1PQ8e3ZfjDe1s=
  - secure: kz493Hi28RK03a414KqZdef8zBsfIA0y1L2LHGKAcoTQclh7S+yQpuTupaXX7CxagP6PmBRUF2gkX56GGDkIupc7iMuacywdA2Ogjmm975xLR+FXeYpQw9TcVibQbxqWLHcTaCnHKVMGs5Lrs+0rBBu4po/TFCIVoTJolHhN3EA=
notifications:
  slack:
    secure: TjkMhFOMgzuy45/lR2N2e20cvKWYoUGJ2uZvGMLia2dLhVp5vwQIe8Tu5V5YvivHlFYH+rxpkhjTy2ygp4+gs0BMkn3QdB6Hxah7m4w04qORcoygoIwCngvtoyRwR5LXbACO5c39TO9A81hsTRGwz/7LuqS8q5W0TzDxsd8wSUI=
